### ISSUE TITLE
高度不是跟着数据伸缩

### ISSUE THREAD

**Issue by sushoulin** [chenfengjw163/vue-json-viewer#10]
是不是可以把盒子里面的max-height：300px去掉

**Comment by chenfengjw163** [comment]
json内容有可能很复杂，所有有一个默认最大高度，点击底部的展开即可展示所有内容

**Comment by mulingyubi** [comment]
我也遇到这个问题，底部展开有时候不会出来，需要点击下其他展开按钮
![image](https://user-images.githubusercontent.com/7279595/54471508-051f2e80-47f5-11e9-83b1-2a3279fb15fa.png)

**Comment by chenfengjw163** [comment]
@mulingyubi 有具体信息吗 比如什么浏览器什么操作系统

**Comment by mulingyubi** [comment]
我用的是mac chrome71，json比较大的情况下，很容易出现
5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chenfengjw163** [comment]
@mulingyubi 我用mac chrome72没有出现你的问题，但我猜测可能是resized事件的dom问题，我改写了触发resized的dom，你可以下载2.1.0尝试下

**Comment by cminl** [comment]
同样初始化的时候展开按钮没有出现

**Comment by cminl** [comment]
![image](https://user-images.githubusercontent.com/30225910/54907133-c76e8400-4f1f-11e9-86b5-cf78b18963fc.png)

**Comment by chenfengjw163** [comment]
@cminl 问题已经解决了，当组件的value在初始化之后再赋值时，下拉箭头状态没有更新，已经发布了2.1.2版本，谢谢你的反馈

**Comment by cminl** [comment]
谢谢大佬
