### ISSUE TITLE
加载json的时候等待时间比较长，最好加载一个loading效果

### ISSUE THREAD

**Issue by MaxxisCZ** [chenfengjw163/vue-json-viewer#12]

**Comment by chenfengjw163** [comment]
是json比较大？还是数据有请求过程，所以等待时间长？
如果是有接口请求的话，可以自己做loading

**Comment by MaxxisCZ** [comment]
是json比较大,解析需要一定时间




------------------ 原始邮件 ------------------
发件人: "陈峰"<notifications@github.com>; 
发送时间: 2019年5月31日(星期五) 晚上10:31
收件人: "chenfengjw163/vue-json-viewer"<vue-json-viewer@noreply.github.com>; 
抄送: "一叶知秋"<876434024@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [chenfengjw163/vue-json-viewer] 加载json的时候等待时间比较长，最好加载一个loading效果 (#12)




是json比较大？还是数据有请求过程，所以等待时间长？
 如果是有接口请求的话，可以自己做loading

**Comment by chenfengjw163** [comment]
2.2.0版本实现了json节点的增量渲染，即使大json文件也可以在第一时间渲染到页面，我测试了一个6.5m的json也可以秒渲染。

**Comment by taxuan-shangguan** [comment]
> 2.2.0版本实现了json节点的增量渲染，即使大json文件也可以在第一时间渲染到页面，我测试了一个6.5m的json也可以秒渲染。

json数据1.3M，expand-depth=5时，渲染卡住，并且一定时间后页面崩溃，当把expand-depth=1时，很快会渲染，并且能快速切换json内容显示。
