### ISSUE TITLE
[FR] highlight links

### ISSUE THREAD

**Issue by machinek56** [chenfengjw163/vue-json-viewer#14]
Hi! Can you add possibility to highlight link in json? Like at screenshot below.
And then add to `<a>` tag target="_blank".
![Assessment Assistant 2019-05-30 19-12-22](https://user-images.githubusercontent.com/12989125/58689166-ef022280-838e-11e9-8ed9-eff992e3fde8.png)

**Comment by chenfengjw163** [comment]
String nodes have added the ability to automatically recognize links

**Comment by machinek56** [comment]
@chenfengjw163 many thanks!
