### ISSUE TITLE
json返回某字段是 19位数字，则显示错误

### ISSUE THREAD

**Issue by MeYoung** [chenfengjw163/vue-json-viewer#16]
例如 {
        "test": 6703338093929759876
      }
则页面显示会出错，超过最大值了。

**Comment by chenfengjw163** [comment]
本地测试过之后并不会报错，json-viewer组件并不会修改或者操作数据的值，只会在渲染之前调用一次这个数字的toString方法，所以我猜测这个报错可能不是组件内报错而是组件外部的一些处理逻辑有些问题。

**Comment by MeYoung** [comment]
嗯 前端失精度问题。
