### ISSUE TITLE
请问使用此插件时 返回的json的字段里有html信息怎么办？ 好像会XSS

### ISSUE THREAD

**Issue by itDjango** [chenfengjw163/vue-json-viewer#18]
![image](https://user-images.githubusercontent.com/20026376/64004097-363fb100-cb40-11e9-91b5-e139cbdc4340.png)
这个是一个完整的html字符串，里面有自动跳转的链接，然后就会跳转走，所以请问可以防XSS吗

**Comment by chenfengjw163** [comment]
vue-json-viewer@2.2.3 以支持xss

**Comment by yangyang-zhang** [comment]
我目前使用的是2.2.19版本，目前还是有xss问题
![image](https://user-images.githubusercontent.com/16460777/128632401-e78c47aa-82ab-4de2-91a7-2ff7a10b8d9a.png)
![image](https://user-images.githubusercontent.com/16460777/128632413-721fd062-642c-4acc-968b-29f5f959bc9c.png)
