### ISSUE TITLE
Bug: Extremely high memory usage

### ISSUE THREAD

**Issue by Adizbek** [chenfengjw163/vue-json-viewer#20]
I have json ~200kb. I displayed it using vue-json-viewer

Memory usage:
![image](https://user-images.githubusercontent.com/10253982/64236017-fd725400-cf12-11e9-9ce7-743d41485bd0.png)

I can provide other informations if you need.

**Comment by chenfengjw163** [comment]
Yes, There is a problem, the dom node still renders when it is not expanded. now @2.2.4 had fix this  problem, you can try it

**Comment by Adizbek** [comment]
Thanks for fast feedback, I will checkout.

**Comment by Adizbek** [comment]
Problem remains the same, no change, I tried minimize all, no effect

**Comment by chenfengjw163** [comment]
e... Are you sure you are using version 2.2.4? I tested json about 240kb, the memory is about 20mb, can you give a code example?

**Comment by Adizbek** [comment]
@chenfengjw163, Sorry my fault. Issue has gone, thank you for fast fix.
