### ISSUE TITLE
Dependency not found: clipboard

### ISSUE THREAD

**Issue by Dids** [chenfengjw163/vue-json-viewer#30]
Suddenly my Vue project is failing to build if I don't manually install `clipboard` and add it to my project's package.json.

```
This dependency was not found:

* clipboard in ./node_modules/vue-json-viewer/vue-json-viewer.js

To install it, you can run: npm install --save clipboard
```

Should `clipboard` be added as a dependency to `vue-json-viewer`, instead of as `peerDependency`? Or perhaps an existing dependency is no longer using it, in which case it doesn't get installed?

**Comment by chenfengjw163** [comment]
The most recent version has been changed to peerDependency. Now I have restored it. I want to deal with it later. Please reinstall it.
