### ISSUE TITLE
能仿照json.cn这个工具进行优化一下吗?

### ISSUE THREAD

**Issue by weiweidong1993** [chenfengjw163/vue-json-viewer#32]
功能性的按钮放在一个固定的位置

![image](https://user-images.githubusercontent.com/53823346/71453851-8c5bf280-27c8-11ea-8499-d92a0f5f7c24.png)

一点小建议,毕竟下拉的时候就找不到 "复制"这个按钮了

**Comment by weiweidong1993** [comment]
![image](https://user-images.githubusercontent.com/53823346/71453903-ce853400-27c8-11ea-947f-3f9c7235f06e.png)

**Comment by weiweidong1993** [comment]
:100

**Comment by chenfengjw163** [comment]
可以，欢迎提供mr
