### ISSUE TITLE
Release and update npm version (v2.2.8)

### ISSUE THREAD

**Issue by crutch12** [chenfengjw163/vue-json-viewer#37]
@chenfengjw163 Hi

Could you please release current master on npm (with new version)?

> v2.1.3 released on 26 Mar 2019 · 41 commits to master since this release

It's not safe to use branch as dependency, because branch can be changed. So we need package update on npm to use new features.

Thanks

**Comment by chenfengjw163** [comment]
done

**Comment by crutch12** [comment]
@chenfengjw163 Thanks!
Provide github release too, please
Because now it's confusing :)
