### ISSUE TITLE
超大整数显示精度问题

### ISSUE THREAD

**Issue by chengboliber** [chenfengjw163/vue-json-viewer#38]
可以支持超过安全值的整数就好了

**Comment by sean8601** [comment]
同求，bigint没法正常显示例如："accountId":4262032868370546739，显示不正常
![image](https://user-images.githubusercontent.com/32088815/80276286-4a14d480-871a-11ea-8405-1daecfbdc3ac.png)

**Comment by chengboliber** [comment]
> 同求，bigint没法正常显示例如："accountId":4262032868370546739，显示不正常
> ![image](https://user-images.githubusercontent.com/32088815/80276286-4a14d480-871a-11ea-8405-1daecfbdc3ac.png)

可以转换成字符串显示，目前只找到这种方式

**Comment by chenfengjw163** [comment]
看了下目前显示大数是OK的呀
![image](https://user-images.githubusercontent.com/7371122/80570073-bb12ff80-8a2c-11ea-940f-514f5efc7b73.png)
![image](https://user-images.githubusercontent.com/7371122/80570093-c534fe00-8a2c-11ea-9a8b-571111866b29.png)

**Comment by sean8601** [comment]
> 看了下目前显示大数是OK的呀
> 
> ![image](https://user-images.githubusercontent.com/7371122/80570073-bb12ff80-8a2c-11ea-940f-514f5efc7b73.png)
> 
> ![image](https://user-images.githubusercontent.com/7371122/80570093-c534fe00-8a2c-11ea-9a8b-571111866b29.png)
> 
> 
> 
> 

你有没注意最后两位变成0了

**Comment by chenfengjw163** [comment]
哦哦 我明白了，但这个精度问题无法解决的，这个大数在存储时就已经失去精度了，展示时无法恢复的，建议在存储时就按照字符串类型去存储

**Comment by xixihappy** [comment]
{
          name: '222',
          com: '333',
          orderNo: '2023030717390244633',
          list: {
            name: 'aaa',
            obj: {
              orderNo: '2023030717390244633'
            }
          }
        }
为什么明明都是字符串型的 前面的显示就直接变int类型了

**Comment by Dudung1018** [comment]
现在只有改变原本数据类型才能解决丢精度问题吗
