### ISSUE TITLE
How to overide Copy method

### ISSUE THREAD

**Issue by carolcoral** [chenfengjw163/vue-json-viewer#41]
I used it in my project and sometimes the value is not a Json but String.It alway be sscaped when i copied it.Like this:
The base data is:
<code>curl -X GET "http://127.0.0.1:18083/admin/test"</code>
When i show it in json-view ,ist like is:
<code>"curl -X GET "http://127.0.0.1:18083/admin/test""</code>
When i used copied:
<code>"curl -X GET \\"http://127.0.0.1:18083/admin/test\""</code>
But what is i really want:
<code>curl -X GET "http://127.0.0.1:18083/admin/test"</code>

**Comment by chenfengjw163** [comment]
Can you customize the processing? You can listen to the `copied` event. In this event, you can get the copied content and reassign it to the clipboard
