### ISSUE TITLE
key排序的时候，将数组的val也进行了排序，理论上不应该对数组进行排序

### ISSUE THREAD

**Issue by ydq** [chenfengjw163/vue-json-viewer#44]
如题，假定有json如下：
```json
{
    "key2":["c","b","a"],
    "key1":"xxx"
}
```

结果排序后的展示变成了（复制倒是没问题）：
~~~json
{
  "key1": "xxx",
  "key2": [
    "a",
    "b",
    "c"
  ]
}
~~~

按理解应该只是对纯 Object 的 key进行排序，不应该对 Array 里面的值也进行排序，本意对json进行format并且按key排序是为了方便快速的在一串大json中找到自己想要的位置，但是如果对数组的值进行了排序如果是想定位问题，就很容易会被误导，因为有的时候后端接口的返回值依赖于前端数组的顺序的。

期待的展示结果 ：
~~~json
{
  "key1": "xxx",
  "key2": [
    "c",
    "b",
    "a"
  ]
}
~~~

**Comment by chenfengjw163** [comment]
数组确实不应该排序，已修复
