### ISSUE TITLE
How to change the default height of the JSON viewer?

### ISSUE THREAD

**Issue by bobfang1992** [chenfengjw163/vue-json-viewer#49]
Hi,

It seems the viewer box is always rendered with the same default height, I am just wondering if there is any way to change it?

Thanks!

**Comment by bobfang1992** [comment]
![img](https://www.awesomescreenshot.com/upload/1137393/1174649/87d58b98-2131-496e-55d1-e5e44b34b15d.png) 

For example, the default rendered JSON viewer has only 300px. I am just wondering if this can be changed to say 500px or even better fill the div container that is wrapping the JSON viewer.

Thanks!

**Comment by chenfengjw163** [comment]
Two ways.
1. customize the entire [https://github.com/chenfengjw163/vue-json-viewer#theming](https://github.com/chenfengjw163/vue-json-viewer#theming) 
2. override the default style

``` style
.jv-container .jv-code.boxed { max-height: 500px } 
```

**Comment by bobfang1992** [comment]
Thanks!
