### ISSUE TITLE
space between key and value

### ISSUE THREAD

**Issue by logliveru** [chenfengjw163/vue-json-viewer#52]
Hi, when i use custom theme spaces between keys and values disappear.
I use vue, vuetify and example my-awesome-json-theme
What am I doing wrong?
![image](https://user-images.githubusercontent.com/8014843/88658777-a225f300-d0dc-11ea-8cd2-316180e2be11.png)

**Comment by chenfengjw163** [comment]
you can use
``` css
.jv-key {
    margin-right: 4px
}
```

**Comment by logliveru** [comment]
Thank you!
