### ISSUE TITLE
Missing clipboard dependency on build

### ISSUE THREAD

**Issue by Tommytrg** [chenfengjw163/vue-json-viewer#53]
I can't build my electron app since I've started using `vue-json-viewer`. I have the following error:

```
Uncaught Error: Cannot find module 'clipboard'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (internal/modules/cjs/loader.js:797)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (reset-search-paths.ts:40)
    at Module._load (internal/modules/cjs/loader.js:690)
    at Module._load (electron/js2c/asar.js:738)
    at Function.Module._load (electron/js2c/asar.js:738)
    at Module.require (internal/modules/cjs/loader.js:852)
    at require (internal/modules/cjs/helpers.js:74)
    at Object.b0c2 (app.364f5d13.js:1)
    at i (app.364f5d13.js:1)
    at chunk-vendors.bb0ac669.js:27`
```
I'm using vue-json-viewer: "2.2.14". I've tried to solve this installing `clipboard: "2.0.4"` but it didn't work.

@chenfengjw163, do you know how to solve this? Is this related with #30?

**Comment by chenfengjw163** [comment]
Clipboard needs to be installed by yourself，it externals in webpack config
``` javascript
externals: {
      vue: 'vue',
      clipboard: 'clipboard'
    }
```

**Comment by Tommytrg** [comment]
I've added `clipboard: "^2.0.6"` but I still have the same error

**Comment by mdealer** [comment]
Same issue here.

**Comment by chenfengjw163** [comment]
let see package.json file, and all electron app?

**Comment by Tommytrg** [comment]
The project where I'm trying to use `vue-json-viewer` is: https://github.com/witnet/sheikah/tree/build in `build` branch. The steps to reproduce this error:

- Clone repository: `git clone https://github.com/Tommytrg/sheikah`
- Install dependencies: `yarn`
- Build app: `yarn electron:build`
- Run the generated build for your platform inside `dist_electron/`
- A blank window should open and show the error in the console with `ctrl + shift + i`

**Comment by chenfengjw163** [comment]
@Tommytrg you can see https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/404
modify ``vue.config.js`` :
``` js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        linux: {
          category: "Network"
        },
      },
      externals: ['clipboard'],
      nodeIntegration: true,
    },
  },
}

```
