### ISSUE TITLE
折叠按钮与横向滚动条冲突问题

### ISSUE THREAD

**Issue by zime-leo** [chenfengjw163/vue-json-viewer#54]
在文本长度很大，而且不换行的情况下，横向滚动条 与 展开/折叠按钮 冲突，点击就会收回面板，横向滚动条无法拖动

**Comment by chenfengjw163** [comment]
能提供个截图嘛

**Comment by zime-leo** [comment]
![20200828104910](https://user-images.githubusercontent.com/70302742/91515676-41c4e400-e91c-11ea-9216-0760b6c9da07.jpg)
截图在这里

**Comment by chenfengjw163** [comment]
明白了，这个滚动应该是你自定义的样式把，那你可以设置一下样式，让滚动栏和展开箭头分离开
``` css
.jv-code {
  margin-bootom: 30px;
}
```

**Comment by zime-leo** [comment]
哦哦，好的，多谢多谢，箭头按钮高度是40px
