### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by reinos** [chenfengjw163/vue-json-viewer#57]
Hi there,

Are you planning to add support for Vue 3?

**Comment by chenfengjw163** [comment]
yeah, i will support in the near future

**Comment by JGaudette** [comment]
hi @chenfengjw163 any update on the vue3 support?  Thanks!

**Comment by qiuquanwu** [comment]
It took me a little time to adapt to vue3. In order not to confuse the original warehouse, I opened a new one：[github](https://github.com/qiuquanwu/vue3-json-viewer) @reinos @chenfengjw163 @JGaudette @HADB

**Comment by JGaudette** [comment]
Thanks @qiuquanwu !  I just tried it and working great so far!

**Comment by chenfengjw163** [comment]
@qiuquanwu 有没有兴趣提一个pr过来，兼容vue3？

**Comment by cloydlau** [comment]
[json-editor-vue](https://github.com/cloydlau/json-editor-vue) 同时支持2和3

**Comment by chenfengjw163** [comment]
done

+vue-json-viewer@3.0
