### ISSUE TITLE
Add ability to collapse/expand long JSON property values

### ISSUE THREAD

**Issue by kami4ka** [chenfengjw163/vue-json-viewer#60]
Hello.
Thanks for this awesome library!

I'd like to ask for the feature: it would be awesome to have the ability to collapse/expand long values (for example, texts longer than 500-1000 characters) so long texts won't clog the viewer. 
Clickable `...` or something like it would fit nicely.

Thanks in advance!

**Comment by chenfengjw163** [comment]
Great idea, let me do it

**Comment by chenfengjw163** [comment]
+ 2.2.16
