### ISSUE TITLE
通过弹出层展示的 Json Viewer 无法复制所渲染的 Json 内容

### ISSUE THREAD

**Issue by BoBo-Git** [chenfengjw163/vue-json-viewer#61]
首先，感谢作者开发的这个库，样式简洁，使用方便。下面是我遇到的问题描述：

需求：
通过按钮点击展示一个弹出层，弹出层里再通过 Props 或者 Http 请求获取要展示的 Json 数据。

问题：
弹出层弹出后，组件可以正常渲染展示数据，但是点击 Copy 并没有正常拷贝渲染出来的数据。

分析：
应该是 v-if 指令导致的 $refs 无法正常获取造成的 Bug。

解决方式：
结合了另一个库 [vue-clipboard2]((https://github.com/Inndy/vue-clipboard2))，用 v-show 控制隐藏一个 textarea，把想要的数据用 JSON.stringify 处理后进行复制。（但复制出来的 Json 没有换行格式）

期望：
期望在这个库里能添加上弹出层展示也能正常复制的支持，谢谢。

**Comment by chenfengjw163** [comment]
v-if不会导致不能复制，是不是render组件后copyable没有设置，copyable需要在初次渲染时设置？

**Comment by chenfengjw163** [comment]
fixed +2.2.19
