### ISSUE TITLE
Copy button is in a bad position

### ISSUE THREAD

**Issue by AllanOricil** [chenfengjw163/vue-json-viewer#65]
If the user does not scroll all the way to the right he will never see the copy button. 

![image](https://user-images.githubusercontent.com/55927613/104133986-ebae8580-537e-11eb-811b-a0a349f6e15e.png)

Could you move it to this position? This way the button is always visible
![image](https://user-images.githubusercontent.com/55927613/104134038-23b5c880-537f-11eb-854d-d0afb2b339a3.png)

**Comment by chenfengjw163** [comment]
Add the "align" attribute to the "copyable" config item, with the values of "left" and "right" to control the left and right alignment.
like
```
<json-viewer
          value={this.jsonData}
          expand-depth={5}
          copyable={{
            align: 'left'
          }}
          boxed
          sort>
</json-viewer>
```

**Comment by chenfengjw163** [comment]
+2.2.18
