### ISSUE TITLE
Bad format when expanding text

### ISSUE THREAD

**Issue by AllanOricil** [chenfengjw163/vue-json-viewer#66]
![image](https://user-images.githubusercontent.com/55927613/104134367-071a9000-5381-11eb-9246-f58d8651afc0.png)

This is how it was mounted on the dom

![image](https://user-images.githubusercontent.com/55927613/104134394-1d285080-5381-11eb-875b-9f5536d883f3.png)

This is how it would like it to be rendered
![image](https://user-images.githubusercontent.com/55927613/104134436-5fea2880-5381-11eb-85cd-c3e22f71f913.png)

**Comment by chenfengjw163** [comment]
Add the "jv-key-node" style class, you can consider setting its style as "display: flex"


+2.2.18
