### ISSUE TITLE
在vue3.0以上版本使用报错

### ISSUE THREAD

**Issue by odomodo** [chenfengjw163/vue-json-viewer#78]
<img width="1003" alt="企业微信截图_16299630881953" src="https://user-images.githubusercontent.com/31067798/130920581-dfdc51b9-937f-4dce-9e2e-c09b69281dea.png">

**Comment by cloydlau** [comment]
用Vue3版 [vue3-json-viewer](https://github.com/qiuquanwu/vue3-json-viewer) ，或者 [json-editor-vue](https://github.com/cloydlau/json-editor-vue) （同时支持2和3）

```vue
<template>
  <JsonEditorVue v-model="value" readonly/>
</template>

<script setup>
import JsonEditorVue from 'json-editor-vue'
</script>
```

**Comment by chenfengjw163** [comment]
done 
+vue-json-viewer@3.0

**Comment by WangHansen** [comment]
3.0.1版本依旧报错

**Comment by chenfengjw163** [comment]
已修复
