### ISSUE TITLE
copyable 不生效是为什么

### ISSUE THREAD

**Issue by Blusez** [chenfengjw163/vue-json-viewer#82]
![image](https://user-images.githubusercontent.com/13349444/140722713-6712a16b-bc44-42c7-aa17-0f0d8b35908d.png)

版本"vue-json-viewer": "^2.2.19",

**Comment by lingtaoluorxhf** [comment]
这个复制按钮好像是有点问题，按照官方的文档配置后，发现是没有效果的。
![image](https://user-images.githubusercontent.com/79630140/141049425-b0124f65-1b86-4e52-a4f2-805e58b9ceeb.png)
**解决方法：**
1.你可以用浏览器的开发者工具看下，会发现右上角其实有个copy按钮的html元素，表面上看起来不奏效，其实是因为这个span标签没有文本内容
![image](https://user-images.githubusercontent.com/79630140/141048371-de476f59-c2cb-4027-ae07-8e7045b5789f.png)
2.查看官方文档可以看到有个插槽可以用
![image](https://user-images.githubusercontent.com/79630140/141049603-bc3257d9-b572-4b97-87ba-70809fab02a0.png)
3.那么可以利用这个插槽来显示按钮文本，然后copy按钮就显示出来了
![image](https://user-images.githubusercontent.com/79630140/141049946-1c171042-77d6-4bd5-ad52-e5e7527bce25.png)
![image](https://user-images.githubusercontent.com/79630140/141050030-2a7bb9a9-db46-4c23-bca0-8136fe11cd3f.png)
效果：
![image](https://user-images.githubusercontent.com/79630140/141050144-3e268312-c523-4622-a0e5-5c10f3bcfed3.png)

**Comment by xxwangkaimin** [comment]
确实呀，最新的版本都不行，必须加上slot才可以
![image](https://user-images.githubusercontent.com/33536543/142962213-27a1045f-fbae-4cc7-99a5-694453113706.png)

**Comment by xxwangkaimin** [comment]
源码示例里面加属性是可以的，但是在自己项目里面是不行的，按照正常流程，加属性和加slot任意一个应该都生效的

**Comment by SealinGp** [comment]
+1 同问题

**Comment by zouchanglin** [comment]
加上slot确实可以解决

**Comment by xiepu1212** [comment]
我是按钮可以显示，但是在Dialog控件下面的copy点了没作用，有人遇到过这种情况吗？

**Comment by lingtaoluo** [comment]
@xiepu1212 你说的这个问题，可能是因为复制的时候挂载点的问题，由于你是弹窗，所以你的复制功能的挂载点需要调整到弹窗的dom。但我不太清楚这个库有没有在这一点做优化。

**Comment by xiepu1212** [comment]
> @xiepu1212 你说的这个问题，可能是因为复制的时候挂载点的问题，由于你是弹窗，所以你的复制功能的挂载点需要调整到弹窗的dom。但我不太清楚这个库有没有在这一点做优化。

我看见我的问题貌似在2.2.19版本已经解决了，我去更新一下看看

**Comment by NGNLzero** [comment]
有个特别搞笑的问题，如果你将你的版本升级为最新版（2.2.22），那么你的这个方法将失效

> 这个复制按钮好像是有点问题，按照官方的文档配置后，发现是没有效果的。 ![image](https://user-images.githubusercontent.com/79630140/141049425-b0124f65-1b86-4e52-a4f2-805e58b9ceeb.png) **解决方法：** 1.你可以用浏览器的开发者工具看下，会发现右上角其实有个copy按钮的html元素，表面上看起来不奏效，其实是因为这个span标签没有文本内容 ![image](https://user-images.githubusercontent.com/79630140/141048371-de476f59-c2cb-4027-ae07-8e7045b5789f.png) 2.查看官方文档可以看到有个插槽可以用 ![image](https://user-images.githubusercontent.com/79630140/141049603-bc3257d9-b572-4b97-87ba-70809fab02a0.png) 3.那么可以利用这个插槽来显示按钮文本，然后copy按钮就显示出来了 ![image](https://user-images.githubusercontent.com/79630140/141049946-1c171042-77d6-4bd5-ad52-e5e7527bce25.png) ![image](https://user-images.githubusercontent.com/79630140/141050030-2a7bb9a9-db46-4c23-bca0-8136fe11cd3f.png) 效果： ![image](https://user-images.githubusercontent.com/79630140/141050144-3e268312-c523-4622-a0e5-5c10f3bcfed3.png)
