### ISSUE TITLE
在展示json对象里面的数组值时，它自动加上了序号，请问如何去掉这些序号？

### ISSUE THREAD

**Issue by lingtaoluo** [chenfengjw163/vue-json-viewer#83]
![image](https://user-images.githubusercontent.com/79630140/141047155-e3f94ab7-642f-44b4-bb81-0efdb1a12dee.png)

**Comment by QianJinGuo** [comment]
I hava the same problem

**Comment by jerossh** [comment]
测试环境没有这个，打包后会出现索引。待解决。

**Comment by jerossh** [comment]
看了下源代码，这是最新版本的添加的特性。版本回调为2.2.19，即可。

**Comment by Microhawk** [comment]
如果有配置项就好了，这样可以自由选择了。

**Comment by chenfengjw163** [comment]
支持了showArrayIndex属性了
